# UI ELEMENTS
#MsgSeparator: ''
#NormalFloat: ''
#NormalNC: ''
#Substitute: ''
#TermCursorNC: ''
ColorColumn: '- cursorLine'
Conceal: 'black'
Cursor: 'background grey'
CursorColumn: '- cursorLine'
CursorIM: '@Cursor'
CursorLine: '- cursorLine'
CursorLineNr: 'grey2 cursorLine'
DiffAdd: 'green visualSel'
DiffChange: 'orange visualSel'
DiffDelete: 'red visualSel'
DiffText: 'yellow visualSel'
Directory: 'cyan'
EndOfBuffer: 'purple background'
ErrorMsg: 'red white'
FoldColumn: 'purple background'
Folded: 'purple background'
IncSearch: 'pureWhite purple'
LineNr: 'grey background'
LspDiagnosticsDefaultError: 'red'
MatchParen: 'pureWhite purple'
ModeMsg: 'purple'
MoreMsg: 'purple'
MsgArea: 'cyan'
NonText: '@EndOfBuffer'
Pmenu: 'foreground background_alt'
PmenuSbar: '- purple'
PmenuSel: 'purple background'
PmenuThumb: '- black'
Question: 'purple'
QuickFixLine: 'foreground cursorLine'
Search: 'yellow2 black2 u'
SignColumn: 'purple background'
SpecialKey: 'orange background'
SpellBad: 'red - u'
SpellCap: 'green - u'
SpellLocal: 'foreground - u'
SpellRare: 'yellow - u'
StatusLine: 'foreground background r'
StatusLineNC: '@StatusLineTermNC'
StatusLineTerm: '@StatusLine'
StatusLineTermNC: 'pureBlack purple r'
TabLine: 'pureBlack grey'
TabLineFill: 'grey pureBlack'
TabLineSel: 'grey2 background'
TermCursor: '@Cursor'
VertSplit: 'pureBlack pureBlack'
Visual: '- visualSel'
VisualNOS: '@Visual'
WarningMsg: 'orange background'
Whitespace: '@EndOfBuffer'
WildMenu: 'pureBlack grey2'
diffAdded: 'purple -'
diffRemoved: 'red -'

# BASE SYNTAX
Boolean: 'yellow'
Character: 'yellow'
Comment: 'blue'     
Conditional: 'green'
Constant: 'yellow' 
Debug: 'purple'
Define: 'purple'
Delimiter: 'foreground'
Error: 'red'
Exception: 'red'
Float: 'yellow'
Function: 'purple'
Identifier: 'green2'
Ignore: 'red'
Include: 'purple'
Keyword: 'purple'
Label: 'cyan'
Macro: 'purple'
Normal: 'foreground background'
Number: 'yellow'
Operator: 'green3'
PreCondit: 'purple'
PreProc: 'purple'
Repeat: 'green'
SpecialChar: 'orange'
SpecialComment: '@Comment'
Special: 'purple'
Statement: 'green'
StorageClass: 'purple'
String: 'yellow'
Structure: 'cyan'
Tag: 'blue'
Title: 'purple'
Todo: 'yellow2 - u - b'
Type: 'cyan'
Typedef: 'cyan'
Underlined: 'green - u'

# LANGUAGE SPECIFICS
# C
cFormat: '@Title'
cCppOutIf1: '@Normal'
cCppOutIf2: '@Normal'
cBracket: '@Title'

# CSS
cssBraces: '@Normal'
cssSelectorOp: 'magenta'

# Haskell
haskellConditional: '@Keyword'
haskellDecl: '@Keyword'
haskellDeclKeyword: '@Keyword'
haskellDeriveKeyword: '@Keyword'
haskellIdentifier: '@Label'
haskellKeyword: '@Keyword'
haskellLet: '@Keyword'
haskellLineComment: '@Comment'
haskellOperators: '@Operator'
haskellType: '@Type'
haskellWhere: '@Keyword'

# Vim
vimGroupName: '@Normal'

# YAML
yamlKeyValueDelimiter: '@Normal'
yamlBlockMappingKey: 'purple'
yamlFlowString: '@String'
yamlFlowStringDelimiter: 'yellow'

# Lua
luaConstant: '@Identifier'
luaFunction: '@Function'
luaFunctionBlock: '@Function'
luaStatement: '@Keyword'
luaCond: '@Keyword'
luaTable: '@Normal'
# PLUGINS
