# COLORS: Foreground Background buri (bold, underlined, reverse ,italic)

# UI ELEMENTS
ColorColumn: '- cursorLine'
CursorColumn: '- cursorLine'
Conceal: 'black'
Cursor: 'background grey'
CursorIM: '@Cursor'
CursorLine: '- cursorLine'
CursorLineNr: 'grey2 cursorLine'
Directory: 'cyan'
DiffAdd: 'green visualSel'
DiffChange: 'orange visualSel'
DiffDelete: 'red visualSel'
DiffText: 'yellow visualSel'
EndOfBuffer: 'purple background'
TermCursor: '@Cursor'
#TermCursorNC: ''
ErrorMsg: 'red white'
VertSplit: 'pureBlack pureBlack'
Folded: 'purple background'
FoldColumn: 'purple background'
SignColumn: 'purple background'
IncSearch: 'pureWhite purple'
#Substitute: ''
LineNr: 'grey background'
MatchParen: 'pureWhite purple'
ModeMsg: 'purple'
MsgArea: 'cyan'
#MsgSeparator: ''
MoreMsg: 'purple'
NonText: '@EndOfBuffer'
#NormalFloat: ''
#NormalNC: ''
Pmenu: 'foreground uiBg'
PmenuSel: 'purple background'
PmenuSbar: '- purple'
PmenuThumb: '- black'
Question: 'purple'
QuickFixLine: 'foreground cursorLine'
Search: 'yellow2 black2 u'
SpecialKey: 'orange background'
SpellBad: 'red - u'
SpellLocal: 'foreground - u'
SpellCap: 'green - u'
SpellRare: 'yellow - u'
StatusLine: 'foreground background r'
StatusLineTerm: '@StatusLine'
StatusLineTermNC: 'pureBlack purple r'
StatusLineNC: '@StatusLineTermNC'
TabLine: 'pureBlack grey'
TabLineFill: 'grey pureBlack'
TabLineSel: 'grey2 background'
Visual: '- visualSel'
VisualNOS: '@Visual'
WarningMsg: 'orange background'
WildMenu: 'pureBlack grey2'
Whitespace: '@EndOfBuffer'
diffAdded: 'purple -'
diffRemoved: 'red -'
LspDiagnosticsDefaultError: 'red'

# BASE SYNTAX
Normal: 'foreground background'
Comment: 'blue'     
Constant: 'yellow' 
Identifier: 'cyan'
Statement: 'green'
PreProc: 'purple'
Type: 'azure'
Special: 'purple'
Underlined: 'green - u'
Error: 'red'
Ignore: 'red'
Delimiter: 'foreground'
Operator: 'green3'
Tag: 'blue'
Debug: 'purple'
StorageClass: 'purple'
String: 'cyan'
Structure: 'cyan'
Typedef: 'azure'
Function: 'green'
Include: 'purple'
Label: 'azure'
Exception: 'orange'
Keyword: 'purple'
SpecialChar: 'orange'
Boolean: 'yellow'
Character: 'yellow'
Float: 'yellow'
Number: 'yellow'
Conditional: 'green'
Repeat: 'green'
Title: 'purple'
Define: 'purple'
Macro: 'purple'
PreCondit: 'purple'
SpecialComment: '@Comment'
Todo: 'yellow - u - b'

# LANGUAGE SPECIFICS
# C
cFormat: '@Title'
cCppOutIf1: '@Normal'
cCppOutIf2: '@Normal'
cBracket: '@Title'

# CSS
cssBraces: '@Normal'
cssSelectorOp: 'magenta'

# Haskell
haskellKeyword: '@Keyword'
haskellDeriveKeyword: '@Keyword'
haskellType: '@Type'
haskellIdentifier: '@Label'
haskellDecl: '@Keyword'
haskellDeclKeyword: '@Keyword'
haskellOperators: '@Operator'
haskellWhere: '@Keyword'
haskellLineComment: '@Comment'
haskellLet: '@Keyword'
haskellConditional: '@Keyword'

#Vim
vimGroupName: '@Normal'

# YAML
yamlKeyValueDelimiter: '@Normal'
yamlBlockMappingKey: '@Function'

# PLUGINS
